# -*- coding: utf-8 -*-
"""nlp_article_summarizer.py.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tBTrHi88vXmiJo0PVSwFR_8DJrh_DtHv

# AI-Powered Multi-Input Article Summarizer using Transformer-Based NLP

### DAY 1:

- Understood the internship task requirements.

- Researched Natural Language Processing (NLP) and text summarization concepts.

- Studied extractive and abstractive summarization techniques.

- Explored transformer models like BART and T5.

- Finalized the project topic:

  “AI-Powered Multi-Input Article Summarizer using Transformer-Based NLP”.

### DAY 2:

- Set up the project environment in Google Colab.

- Installed required libraries:
  transformers, torch, sentencepiece, PyPDF2, newspaper3k, and lxml_html_clean.

- Imported all required Python modules successfully.

- Verified library installation and environment setup.
"""

!pip install transformers==4.41.2
!pip install torch
!pip install sentencepiece
!pip install accelerate
!pip install PyPDF2
!pip install newspaper3k
!pip install lxml_html_clean

"""### DAY 3:

- Integrated the pretrained BART transformer model using Hugging Face Transformers.

- Loaded the AI summarization pipeline.

- Tested the model using sample article text.

- Successfully generated AI-based summaries.
"""

# Import transformer pipeline
from transformers import pipeline

# Import PDF reader library
from PyPDF2 import PdfReader
from newspaper import Article

# Load pretrained BART summarization model
summarizer = pipeline(
    task="summarization",
    model="facebook/bart-large-cnn"
)

"""### DAY 4:

- Developed the text summarization module.

- Implemented dynamic user text input functionality.

- Created a summarization function with optimized parameters.

- Tested summarization on lengthy text articles.
"""

# Function to generate AI summary
def summarize_text(text):

    summary = summarizer(
        text,
        max_length=250,
        min_length=100,
        do_sample=False
    )

    return summary[0]['summary_text']

import textwrap

text = input("Paste your article:\n\n")

summary = summarize_text(text)

print("\n===== SUMMARY =====\n")

wrapped_text = textwrap.fill(summary, width=100)

print(wrapped_text)

"""### DAY 5:

- Implemented PDF upload functionality.

- Extracted textual data from PDF files using PyPDF2.

- Connected extracted PDF content with the transformer summarization model.

- Successfully generated summaries from PDF documents.
"""

from google.colab import files

uploaded = files.upload()

try:
    reader = PdfReader(pdf_file)

except:
    print("Unable to read PDF")

pdf_file = list(uploaded.keys())[0]
# Read uploaded PDF file
reader = PdfReader(pdf_file)
# Extract text from all PDF pages
pdf_text = ""

for page in reader.pages:
    pdf_text += page.extract_text()

import textwrap

summary = summarize_text(pdf_text[:3000])

print("\n===== PDF SUMMARY =====\n")

wrapped_text = textwrap.fill(summary, width=100)

print(wrapped_text)

"""### DAY 6:

- Developed website/article URL summarization functionality.

- Implemented article extraction using newspaper3k.

- Tested summarization using online article links.

- Improved URL text extraction workflow.
"""

# Import article extraction library
from newspaper import Article
url = "https://en.wikipedia.org/wiki/Artificial_intelligence"
# Create article object using URL
article = Article(url)
# Download and parse article content
article.download()
article.parse()
# Extract article text
article_text = article.text

print(article_text[:3000])

try:
    article.download()
    article.parse()

except:
    print("Invalid or unsupported URL")

import textwrap

summary = summarize_text(article_text[:3000])

print("\n===== WEBSITE SUMMARY =====\n")

wrapped_text = textwrap.fill(summary, width=100)

print(wrapped_text)

"""### DAY 7:

- Performed testing on text summarization using different article inputs.

- Tested PDF upload and summary generation functionality.

- Verified output quality for website/article summarization.

- Identified issues related to URL extraction and transformer input limits.

### DAY 8:

- Added exception handling and error management for invalid URLs and extraction failures.

- Optimized transformer input length handling to avoid token limit issues.

- Improved overall processing stability and summary quality.

- Fixed minor bugs identified during testing.

## Conclusion

The project successfully demonstrates the implementation of an AI-powered multi-input article summarization system using Natural Language Processing and transformer-based models. The developed tool is capable of generating concise and meaningful summaries from multiple input sources including plain text, PDF documents, and website articles.

The project uses the pretrained BART transformer model from Hugging Face Transformers to perform abstractive text summarization efficiently without requiring manual model training. Additional functionalities such as PDF text extraction, URL article extraction, and error handling were also integrated to improve the overall usability and stability of the system.

This project helped in understanding important NLP concepts such as text preprocessing, transformer architectures, abstractive summarization, and real-world text processing workflows. The developed system reduces manual effort required to read lengthy documents and demonstrates the practical application of Artificial Intelligence in content summarization tasks.
"""
